version: '2'

services:

  jenkins:
    image: jenkins/jenkins:2.426.2-jdk17
    volumes:
       - jenkins_data:/var/jenkins_home
    networks:
      - jenkins
    network-alias:
      - docker
    ports:
      - '8080:8080'
      - '50000:50000'

  sonarqube:
    image: sonarqube:7.6-community 
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    networks:
      - jenkins
    ports:
      - '9000:9000'
    environment:
      - sonar.jdbc.username=admin
      - sonar.jdbc.password=admin1

  dind:
    image: docker:dind
    privileged: true
    networks:
      jenkins:
        aliases:
          - docker
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client
    ports:
      - '2376:2376'

    